name: Destroy Dev Infrastructure
on:
    workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: "${{secrets.ARM_CLIENT_ID}}"
  ARM_CLIENT_SECRET: "${{secrets.ARM_CLIENT_SECRET}}"
  ARM_SUBSCRIPTION_ID: "${{secrets.ARM_SUBSCRIPTION_ID}}"
  ARM_TENANT_ID: "${{secrets.ARM_TENANT_ID}}"
  TF_VAR_port: "${{ secrets.TF_VAR_PORT }}"
  TF_VAR_mongo_url: "${{ secrets.TF_VAR_MONGO_URL }}"
  TF_VAR_mail_service: "${{ secrets.TF_VAR_MAIL_SERVICE }}"
  TF_VAR_mail_secret_key: "${{ secrets.TF_VAR_MAIL_SECRET_KEY }}"
  TF_VAR_mail_user: "${{ secrets.TF_VAR_MAIL_USER }}"
  TF_VAR_mapbox_access_token: "${{ secrets.TF_VAR_MAPBOX_ACCESS_TOKEN }}"
  TF_VAR_default_image_url: "${{ secrets.TF_VAR_DEFAULT_IMAGE_URL }}"
  TF_VAR_domain: "${{ secrets.TF_VAR_DOMAIN }}"
  TF_VAR_mongo_initdb_root_username: "${{ secrets.TF_VAR_MONGO_INITDB_ROOT_USERNAME }}"
  TF_VAR_mongo_initdb_root_password: "${{ secrets.TF_VAR_MONGO_INITDB_ROOT_PASSWORD }}"

jobs:
  terraform-plan-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
            
      - name: Create SSH Keys from secrets
        run: |
          mkdir -p ./env/dev/keys
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./env/dev/keys/UniPlaces_Server
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./env/dev/keys/UniPlaces_Server.pub
          chmod 777 ./env/dev/keys/UniPlaces_Server
          chmod 777 ./env/dev/keys/UniPlaces_Server.pub
          
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2
          terraform_wrapper: false
            
      - name: Terraform Init
        run: terraform -chdir=env/dev init

      - name: Terraform destroy
        run: terraform -chdir=env/dev destroy --auto-approve